// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SklepInternetowy.Data;

#nullable disable

namespace SklepInternetowy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SklepInternetowy.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Wielowątkowa, diaboliczna opowieść o tym jak szlachetne idee indywidualnej wolności w umysłach ludzi na wolność niegotowych, kształtowanych w uściskach carskiego samodzierżawia, przeradzają się w idee nihilizmu, bezwładne rewolucyjne ruchy i terroryzm.",
                            Name = "Dostojewski- Biesy",
                            Price = 30
                        },
                        new
                        {
                            Id = 2,
                            Description = "Późne, dojrzałe dzieło wielkiego pisarza stanowi kwintesencję jego poglądów na życie i sztukę. Dowodem na uniwersalność i doniosłość przesłania powieści jest uhonorowanie jej międzynarodową nagrodą Prix Formentor, najwyższym europejskim wyróżnieniem po Literackiej Nagrodzie Nobla",
                            Name = "Gombrowicz- Kosmos",
                            Price = 35
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cudze słowa uwodzą wizją śródziemnomorskiej wyspy szczęśliwej i krakowskich mglistych Plant, pachną świeżo pieczonym chlebem i pilawem z jagnięciną. Powoli odkrywają przed czytelnikiem tajemnicę notesów, pełnych cudzych słów.",
                            Name = "Szostak- Cudze Słowa",
                            Price = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
